[project]
name = "proton-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "ollama-python>=0.1.2",
    "protonmail-api-client>=2.1.1",
    "python-dotenv>=1.0.1",
]
